# This file was generated by cronoboost.
#
# To create tasks, that will be executed by cronoboost,
# just add some lines in this file.
#
# E.g.
# `daily -> { puts 'Hello World' } # this executes the lambda once a day
# `at :my_smart_function, Time.zone.now # this executes the my_smart_function method every day at the given time
